In [17]:
with open('input_day5.txt', 'r') as f:
    coords = []
    for line in f.readlines():
        line = line.replace('->', ',').strip().split(',')
        line = [( int(line[0]), int(line[1]) ),
                ( int(line[2]), int(line[3]) )
               ]
        coords.append(line)
        print(line)

[(0, 9), (5, 9)]
[(8, 0), (0, 8)]
[(9, 4), (3, 4)]
[(2, 2), (2, 1)]
[(7, 0), (7, 4)]
[(6, 4), (2, 0)]
[(0, 9), (2, 9)]
[(3, 4), (1, 4)]
[(0, 0), (8, 8)]
[(5, 5), (8, 2)]


In [25]:
horiz_lines = []
vert_lines = []

for line in coords:
    if line[0][1] == line[1][1]:
        horiz_lines.append(line)
    elif line[0][0] == line[1][0]:
        vert_lines.append(line)
print('Horizontal lines:')
print(horiz_lines)
print('Vertical lines:')
print(vert_lines)


Horizontal lines:
[[(0, 9), (5, 9)], [(9, 4), (3, 4)], [(0, 9), (2, 9)], [(3, 4), (1, 4)]]
Vertical lines:
[[(2, 2), (2, 1)], [(7, 0), (7, 4)]]


Sort the points in each line, from left to right, from down to up

In [33]:
sorted_h_lines = []

# define start and end point within each line
for line in horiz_lines:
    line = sorted(line, key = lambda x: x[0])
    sorted_h_lines.append(line)

sorted_h_lines = sorted(sorted_h_lines, key = lambda x: x[0][1])

sorted_v_lines = []
for line in vert_lines:
    line = sorted(line, key = lambda x: x[1])
    sorted_v_lines.append(line)

sorted_v_lines = sorted(sorted_v_lines, key = lambda x: x[0][0])

Print the sorted lines in a appropiate way:

In [34]:
print('Horizontal lines:')
for h_line in sorted_h_lines:
    print(f'{h_line[0]} --> {h_line[1]}')
print('Vertical lines:')
for v_line in sorted_v_lines:
    print(f'{v_line[0]} --> {v_line[1]}')

Horizontal lines:
(3, 4) --> (9, 4)
(1, 4) --> (3, 4)
(0, 9) --> (5, 9)
(0, 9) --> (2, 9)
Vertical lines:
(2, 1) --> (2, 2)
(7, 0) --> (7, 4)


In [36]:
# _2dplot dictionary: {point: times point is crossed}
_2dplot = {}
plot =[]
# adding horizontal points to the 2D plot
for h_line in sorted_h_lines:
    y_coord = h_line[0][1]
    x1 = h_line[0][0] # start point
    x2 = h_line[1][0] # finish point
    # create all points between start and finish
    for x_coord in range(x1,x2+1):
        point = (x_coord, y_coord)
        if point in _2dplot.keys():
            _2dplot[point] += 1
        else:
            _2dplot[point] = 1
        plot.append(point)
# adding horizontal points to the 2D plot
for v_line in sorted_v_lines:
    x_coord = h_line[0][0]
    y1 = h_line[0][1] # start point
    y2 = h_line[1][1] # finish point
    # create all points between start and finish
    for y_coord in range(y1,y2+1):
        point = (x_coord, y_coord)
        if point in _2dplot.keys():
            _2dplot[point] += 1
        else:
            _2dplot[point] = 1
        plot.append(point)

[(3, 4), (4, 4), (5, 4), (6, 4), (7, 4), (8, 4), (9, 4), (1, 4), (2, 4), (3, 4), (0, 9), (1, 9), (2, 9), (3, 9), (4, 9), (5, 9), (0, 9), (1, 9), (2, 9), (0, 9), (0, 9)]


In [55]:
import numpy as np
unique_points = set(plot)
x_coords = [i[0] for i in unique_points]
y_coords = [i[1] for i in unique_points]
min_x, min_y = min(x_coords), min(y_coords)
max_x, max_y = max(x_coords), max(y_coords)
width = max_x + 1
height = max_y +1 
map = np.zeros((width, height))

In [52]:
print(min_x, max_x)
print(min_y, max_y)


0 9
4 9


In [59]:
for point in unique_points:
    map[point] = plot.count(point)
print(map)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 4.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 2.]
 [0. 0. 0. 0. 2. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]
